name = "Bezier"
uuid = "cca68bfe-95f8-4ee5-bb6d-238a9e60a0c8"
authors = ["Olli Wilkman <olli.wilkman@iki.fi>"]
version = "0.6.1"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
